//
// Created by Arnab on 06-11-2019.
//

#ifndef TRAVELRIGHT_TRAVELDATA_H
#define TRAVELRIGHT_TRAVELDATA_H

#endif //TRAVELRIGHT_TRAVELDATA_H

static int SELECTED_PACKAGE_TYPE;
static int SELECTED_DESTINATION;
static int SELECTED_CLASS_OF_TRAVEL;

